# Inspection of data

### notes on what transformations are done

 - columns with only nan deleted
 - columns with no variance deleted
 - normalized values

In [16]:
# imports
import pandas as pd

In [17]:
training = pd.read_csv("../data/original/training.csv", delimiter = ";")
holdout = pd.read_csv("../data/original/holdout.csv", delimiter = ";")

In [18]:
training.head(5)

,virksomhedsRegistreringsId,target,ejerkreds_aktiv_93,ejerkreds_aktiv_92,ejerkreds_aktiv_94,virksomhedsoplysninger_17,virksomhedsoplysninger_2,virksomhedsoplysninger_4,virksomhedsoplysninger_3,virksomhedsoplysninger_1,...,risikomarkering_21,risikomarkering_23,risikomarkering_6,ejerkreds_aktiv_9,sagsoplysninger_2,ejerkreds_aktiv_8,sagsoplysninger_1,sagsoplysninger_30,risikomarkering_1,sagsoplysninger_36
0,1,target_FALSE,NaN,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,-79,NaN,NaN,0,0,2
1,2,target_FALSE,NaN,0,0,12.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,NaN,-30,NaN,NaN,0,0,2
2,5,target_FALSE,NaN,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,-135,NaN,NaN,0,0,2
3,6,target_TRUE,NaN,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0,0,2
4,7,target_FALSE,NaN,1,1,1.0,1.0,1.0,0.0,1.0,...,NaN,NaN,NaN,NaN,-21,NaN,NaN,1,0,2

In [19]:
# target shows whether the company was created for fraudulent purposes or not
# converting target variables to just True and False
target_new = list()

for idx, row in training.iterrows():
    target = row['target']
    if target == "target_FALSE":
        target_new.append(False)
    elif target == "target_TRUE":
        target_new.append(True)

training.drop('target', axis=1, inplace=True)
training['target'] = target_new

training['target']

0        False
1        False
2        False
3         True
4        False
         ...
13714    False
13715     True
13716    False
13717     True
13718    False
Name: target, Length: 13719, dtype: bool

In [20]:
# print all columns with 3 example samples
for (columnName, columnData) in training.iteritems():
    print(columnName)
    print(columnData.values[:3])
    print(type(str(columnData.values[0])))
    print()

virksomhedsRegistreringsId
[1 2 5]
<class 'str'>

ejerkreds_aktiv_93
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_92
[0 0 0]
<class 'str'>

ejerkreds_aktiv_94
[0 0 0]
<class 'str'>

virksomhedsoplysninger_17
[nan 12. nan]
<class 'str'>

virksomhedsoplysninger_2
[nan  0. nan]
<class 'str'>

virksomhedsoplysninger_4
[nan  0. nan]
<class 'str'>

virksomhedsoplysninger_3
[nan  0. nan]
<class 'str'>

virksomhedsoplysninger_1
[nan  0. nan]
<class 'str'>

virksomhedsoplysninger_19
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_18
[nan 30. nan]
<class 'str'>

virksomhedsoplysninger_21
[ 0. nan  0.]
<class 'str'>

virksomhedsoplysninger_22
['-5,00e+06' nan '-5,00e+06']
<class 'str'>

virksomhedsoplysninger_25
['-1,0e+06' nan '0,0e+00']
<class 'str'>

virksomhedsoplysninger_24
['2,87250000000000e-02' nan '0,00000000000000e+00']
<class 'str'>

virksomhedsoplysninger_23
['23,89750000000000' nan '12,95000000000000']
<class 'str'>

virksomhedsoplysninger_20
[-500000.      nan       0.]
<class 'str'>

ejerkreds_aktiv_83
[nan '4,2' nan]
<class 'str'>

ejerkreds_aktiv_16
[ 0. nan  0.]
<class 'str'>

ejerkreds_aktiv_18
['-5,0e+06' nan '-5,0e+06']
<class 'str'>

ejerkreds_aktiv_24
['-1,0e+06' nan '0,0e+00']
<class 'str'>

ejerkreds_aktiv_22
['3,83000000000000e-02' nan '0,00000000000000e+00']
<class 'str'>

ejerkreds_aktiv_20
['13,14000000000000' nan '12,95000000000000']
<class 'str'>

ejerkreds_aktiv_14
[-500000.      nan       0.]
<class 'str'>

ejerkreds_aktiv_15
[ 0. nan  0.]
<class 'str'>

ejerkreds_aktiv_17
['-1,0e+06' nan '-1,0e+06']
<class 'str'>

ejerkreds_aktiv_23
[-50000.     nan      0.]
<class 'str'>

ejerkreds_aktiv_21
['0,0383' nan '0,0000']
<class 'str'>

ejerkreds_aktiv_19
['13,14' nan '12,95']
<class 'str'>

ejerkreds_aktiv_13
[-20000.     nan      0.]
<class 'str'>

ejerkreds_aktiv_62
[ 0. nan  0.]
<class 'str'>

ejerkreds_ny_13
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_64
['-5,0e+06' nan '-5,0e+06']
<class 'str'>

ejerkreds_ny_15
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_70
['-1,0e+06' nan '0,0e+00']
<class 'str'>

ejerkreds_ny_21
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_68
['3,83000000000000e-02' nan '0,00000000000000e+00']
<class 'str'>

ejerkreds_ny_19
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_66
['13,14000000000000' nan '12,95000000000000']
<class 'str'>

ejerkreds_ny_17
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_60
[-500000.      nan       0.]
<class 'str'>

ejerkreds_ny_11
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_61
[ 0. nan  0.]
<class 'str'>

ejerkreds_ny_12
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_63
['-1,0e+06' nan '-1,0e+06']
<class 'str'>

ejerkreds_ny_14
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_69
[-50000.     nan      0.]
<class 'str'>

ejerkreds_ny_20
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_67
['0,0383' nan '0,0000']
<class 'str'>

ejerkreds_ny_18
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_65
['13,14' nan '12,95']
<class 'str'>

ejerkreds_ny_16
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_59
[-20000.     nan      0.]
<class 'str'>

ejerkreds_ny_10
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_10
[0. 0. 0.]
<class 'str'>

ejerkreds_aktiv_31
[4. 2. 4.]
<class 'str'>

ejerkreds_aktiv_96
[4. 1. 1.]
<class 'str'>

ejerkreds_aktiv_97
[ 3. nan nan]
<class 'str'>

ejerkreds_aktiv_47
[4 4 6]
<class 'str'>

ejerkreds_aktiv_12
[3 1 1]
<class 'str'>

ejerkreds_aktiv_48
[1 1 4]
<class 'str'>

ejerkreds_aktiv_50
[1 2 4]
<class 'str'>

ejerkreds_aktiv_49
[1 1 4]
<class 'str'>

ejerkreds_aktiv_3
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_2
[ 1. nan nan]
<class 'str'>

ejerkreds_aktiv_27
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_29
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_32
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_124
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_28
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_30
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_33
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_125
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_1
[ 2. 12. 11.]
<class 'str'>

ejerkreds_aktiv_130
[0. 0. 0.]
<class 'str'>

ejerkreds_aktiv_129
[0. 0. 0.]
<class 'str'>

ejerkreds_aktiv_128
[0. 0. 0.]
<class 'str'>

ejerkreds_aktiv_127
[0. 0. 0.]
<class 'str'>

ejerkreds_aktiv_7
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_6
[1496.   30.  864.]
<class 'str'>

ejerkreds_ny_8
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_11
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_41
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_43
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_44
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_45
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_46
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_35
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_36
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_37
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_38
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_39
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_40
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_131
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_42
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_99
[nan nan nan]
<class 'str'>

ejerkreds_ny_44
[nan nan nan]
<class 'str'>

ejerkreds_tidligere_10
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_87
[nan nan nan]
<class 'str'>

ejerkreds_ny_37
[nan nan nan]
<class 'str'>

ejerkreds_tidligere_8
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_53
[nan nan nan]
<class 'str'>

ejerkreds_ny_3
[nan nan nan]
<class 'str'>

ejerkreds_tidligere_2
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_25
['-25307,0000000000' '-25537,0000000000' '-25432,0000000000']
<class 'str'>

ejerkreds_aktiv_26
[-25307. -25537. -25432.]
<class 'str'>

ejerkreds_aktiv_126
[3. 1. 1.]
<class 'str'>

ejerkreds_ny_70
[nan nan nan]
<class 'str'>

ejerkreds_tidligere_16
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_104
[200000. 700000.      0.]
<class 'str'>

ejerkreds_ny_50
[nan nan nan]
<class 'str'>

ejerkreds_tidligere_12
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_121
['-2,82903331724583e-01' '-9,14656010208043e-02' nan]
<class 'str'>

ejerkreds_ny_66
[nan nan nan]
<class 'str'>

ejerkreds_tidligere_13
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_103
['0,0e+00' '-5,0e+06' '0,0e+00']
<class 'str'>

ejerkreds_ny_49
[nan nan nan]
<class 'str'>

ejerkreds_tidligere_11
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_82
['0,3333333333333333' '0,0000000000000000' '1,0000000000000000']
<class 'str'>

ejerkreds_ny_30
[nan nan nan]
<class 'str'>

ejerkreds_tidligere_7
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_107
[45000.    nan 40000.]
<class 'str'>

ejerkreds_ny_53
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_106
[40000.    nan 35000.]
<class 'str'>

ejerkreds_ny_52
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_114
[400000.     nan 400000.]
<class 'str'>

ejerkreds_ny_60
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_112
[500000.     nan 400000.]
<class 'str'>

ejerkreds_ny_58
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_113
[nan nan nan]
<class 'str'>

ejerkreds_ny_59
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_111
[ 800000.      nan 1500000.]
<class 'str'>

ejerkreds_ny_57
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_110
[800000.     nan 800000.]
<class 'str'>

ejerkreds_ny_56
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_117
[ 60000.     nan 220000.]
<class 'str'>

ejerkreds_ny_63
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_116
[ 0. nan nan]
<class 'str'>

ejerkreds_ny_62
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_109
[nan nan nan]
<class 'str'>

ejerkreds_ny_55
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_108
[nan nan nan]
<class 'str'>

ejerkreds_ny_54
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_55
[nan nan nan]
<class 'str'>

ejerkreds_ny_5
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_84
[nan nan nan]
<class 'str'>

ejerkreds_ny_31
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_95
[nan nan nan]
<class 'str'>

ejerkreds_ny_42
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_118
[nan nan nan]
<class 'str'>

ejerkreds_ny_69
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_115
[nan nan  0.]
<class 'str'>

ejerkreds_ny_61
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_89
[52000. 52000.    nan]
<class 'str'>

ejerkreds_ny_39
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_85
[nan nan nan]
<class 'str'>

ejerkreds_ny_35
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_101
[1000.   nan   nan]
<class 'str'>

ejerkreds_ny_46
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_54
[4500. 5000.   nan]
<class 'str'>

ejerkreds_ny_4
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_56
[nan  0. nan]
<class 'str'>

ejerkreds_ny_6
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_81
[nan nan nan]
<class 'str'>

ejerkreds_ny_29
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_58
[nan nan nan]
<class 'str'>

ejerkreds_ny_9
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_100
[nan nan nan]
<class 'str'>

ejerkreds_ny_45
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_52
[nan nan nan]
<class 'str'>

ejerkreds_ny_2
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_74
[nan nan nan]
<class 'str'>

ejerkreds_ny_25
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_72
[0. 0. 0.]
<class 'str'>

ejerkreds_ny_23
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_73
[nan nan nan]
<class 'str'>

ejerkreds_ny_24
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_88
[     0.      0. 500000.]
<class 'str'>

ejerkreds_ny_38
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_91
['0,0e+00' '4,0e+06' '0,0e+00']
<class 'str'>

ejerkreds_ny_41
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_90
['0,0e+00' '2,0e+06' '0,0e+00']
<class 'str'>

ejerkreds_ny_40
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_105
[nan nan nan]
<class 'str'>

ejerkreds_ny_51
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_71
[ 5000. 10000.  5000.]
<class 'str'>

ejerkreds_ny_22
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_86
[nan nan nan]
<class 'str'>

ejerkreds_ny_36
[nan nan nan]
<class 'str'>

ejerkreds_tidligere_6
[nan nan nan]
<class 'str'>

ejerkreds_tidligere_15
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_79
[nan nan nan]
<class 'str'>

ejerkreds_ny_28
[nan nan nan]
<class 'str'>

ejerkreds_tidligere_5
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_98
[nan nan nan]
<class 'str'>

ejerkreds_ny_43
[nan nan nan]
<class 'str'>

ejerkreds_tidligere_9
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_122
[nan nan nan]
<class 'str'>

ejerkreds_ny_68
[nan nan nan]
<class 'str'>

ejerkreds_tidligere_14
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_51
[nan nan nan]
<class 'str'>

ejerkreds_ny_1
[nan nan nan]
<class 'str'>

ejerkreds_tidligere_1
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_80
[0. 0. 0.]
<class 'str'>

ejerkreds_aktiv_102
[0. 0. 0.]
<class 'str'>

ejerkreds_aktiv_78
[0 0 0]
<class 'str'>

ejerkreds_ny_32
[0. 0. 0.]
<class 'str'>

ejerkreds_aktiv_34
[0. 0. 0.]
<class 'str'>

ejerkreds_aktiv_5
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_75
[nan nan nan]
<class 'str'>

ejerkreds_ny_26
[nan nan nan]
<class 'str'>

ejerkreds_tidligere_3
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_76
[nan nan nan]
<class 'str'>

ejerkreds_ny_27
[nan nan nan]
<class 'str'>

ejerkreds_tidligere_4
[nan nan nan]
<class 'str'>

ejerkreds_ny_48
[nan nan nan]
<class 'str'>

ejerkreds_ny_47
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_123
['0,0000000000000000' '0,0000000000000000' '0,0000000000000000']
<class 'str'>

ejerkreds_ny_67
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_57
['0,000000000000000' '0,000000000000000' '0,000000000000000']
<class 'str'>

ejerkreds_ny_7
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_120
[0. 0. 0.]
<class 'str'>

ejerkreds_ny_65
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_119
[0. 0. 0.]
<class 'str'>

ejerkreds_ny_64
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_4
[nan nan nan]
<class 'str'>

adresse_1
[ 1.  1. nan]
<class 'str'>

adresse_2
[1. 1. 3.]
<class 'str'>

adresse_3
[1. 1. 3.]
<class 'str'>

adresse_4
[1. 1. 3.]
<class 'str'>

adresse_16
[nan nan nan]
<class 'str'>

ejerkreds_ny_33
[nan nan nan]
<class 'str'>

adresse_15
[ 1.  1. nan]
<class 'str'>

adresse_5
[nan nan nan]
<class 'str'>

adresse_6
[nan nan nan]
<class 'str'>

adresse_10
[nan nan nan]
<class 'str'>

adresse_11
[nan nan nan]
<class 'str'>

adresse_7
[nan nan nan]
<class 'str'>

adresse_12
[nan nan nan]
<class 'str'>

adresse_9
[nan nan nan]
<class 'str'>

adresse_14
[nan nan nan]
<class 'str'>

adresse_8
[nan nan nan]
<class 'str'>

adresse_13
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_55
[4 6 9]
<class 'str'>

virksomhedsoplysninger_54
[ 5  5 10]
<class 'str'>

virksomhedsoplysninger_5
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_10
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_12
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_7
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_8
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_9
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_13
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_11
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_6
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_26
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_27
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_28
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_29
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_34
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_35
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_36
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_30
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_31
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_32
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_33
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_37
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_38
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_49
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_40
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_52
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_48
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_45
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_39
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_51
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_44
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_41
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_43
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_46
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_42
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_50
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_53
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_47
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_14
[nan 12. nan]
<class 'str'>

virksomhedsoplysninger_15
[nan nan nan]
<class 'str'>

virksomhedsoplysninger_16
[ nan  30. 135.]
<class 'str'>

sagsoplysninger_37
[nan nan nan]
<class 'str'>

sagsoplysninger_3
[0 0 0]
<class 'str'>

sagsoplysninger_15
[0 0 0]
<class 'str'>

ejerkreds_ny_34
[0 0 0]
<class 'str'>

sagsoplysninger_14
[1 1 1]
<class 'str'>

sagsoplysninger_12
[1 1 1]
<class 'str'>

sagsoplysninger_13
[1 1 1]
<class 'str'>

sagsoplysninger_16
[nan nan nan]
<class 'str'>

sagsoplysninger_21
[nan nan nan]
<class 'str'>

sagsoplysninger_24
[nan nan nan]
<class 'str'>

sagsoplysninger_26
[nan nan nan]
<class 'str'>

sagsoplysninger_27
[nan nan nan]
<class 'str'>

sagsoplysninger_28
[nan nan nan]
<class 'str'>

sagsoplysninger_17
[nan nan nan]
<class 'str'>

sagsoplysninger_18
[nan nan nan]
<class 'str'>

sagsoplysninger_19
[nan nan nan]
<class 'str'>

sagsoplysninger_20
[nan nan nan]
<class 'str'>

sagsoplysninger_22
[nan nan nan]
<class 'str'>

sagsoplysninger_23
[nan nan nan]
<class 'str'>

sagsoplysninger_25
[1 1 1]
<class 'str'>

sagsoplysninger_31
[nan nan nan]
<class 'str'>

sagsoplysninger_32
[nan nan nan]
<class 'str'>

sagsoplysninger_33
[nan nan nan]
<class 'str'>

sagsoplysninger_6
[ 1. nan nan]
<class 'str'>

sagsoplysninger_7
[nan nan nan]
<class 'str'>

sagsoplysninger_8
[1 1 1]
<class 'str'>

sagsoplysninger_9
[nan nan nan]
<class 'str'>

sagsoplysninger_10
[nan nan nan]
<class 'str'>

sagsoplysninger_11
[nan nan nan]
<class 'str'>

sagsoplysninger_34
[nan nan nan]
<class 'str'>

sagsoplysninger_5
[nan nan nan]
<class 'str'>

sagsoplysninger_35
[nan nan nan]
<class 'str'>

sagsoplysninger_4
[nan nan nan]
<class 'str'>

risikomarkering_2
[nan nan nan]
<class 'str'>

risikomarkering_3
[nan nan nan]
<class 'str'>

risikomarkering_5
[nan nan nan]
<class 'str'>

risikomarkering_7
[nan nan nan]
<class 'str'>

risikomarkering_8
[nan nan nan]
<class 'str'>

risikomarkering_10
[nan nan nan]
<class 'str'>

risikomarkering_11
[nan nan nan]
<class 'str'>

risikomarkering_12
[nan nan nan]
<class 'str'>

risikomarkering_13
[nan nan nan]
<class 'str'>

risikomarkering_14
[nan nan nan]
<class 'str'>

risikomarkering_16
[nan nan nan]
<class 'str'>

risikomarkering_17
[nan nan nan]
<class 'str'>

risikomarkering_18
[nan nan nan]
<class 'str'>

risikomarkering_19
[nan nan nan]
<class 'str'>

risikomarkering_20
[nan nan nan]
<class 'str'>

risikomarkering_21
[nan  1. nan]
<class 'str'>

risikomarkering_23
[nan nan nan]
<class 'str'>

risikomarkering_6
[nan nan nan]
<class 'str'>

ejerkreds_aktiv_9
[nan nan nan]
<class 'str'>

sagsoplysninger_2
[ -79  -30 -135]
<class 'str'>

ejerkreds_aktiv_8
[nan nan nan]
<class 'str'>

sagsoplysninger_1
[nan nan nan]
<class 'str'>

sagsoplysninger_30
[0 0 0]
<class 'str'>

risikomarkering_1
[0 0 0]
<class 'str'>

sagsoplysninger_36
[2 2 2]
<class 'str'>

target
[False False False]
<class 'str'>

In [21]:
# printing nan percentages
row_count = training.shape[0]
for (columnName, columnData) in training.iteritems():
    print(columnName)
    
    nan_count = 0
    for point in columnData:
        point = str(point)
        if point == "nan":
            nan_count+=1
    
    nan_percent = nan_count/row_count
    print(nan_percent)
    print()

virksomhedsRegistreringsId
0.0

ejerkreds_aktiv_93
1.0

ejerkreds_aktiv_92
0.0

ejerkreds_aktiv_94
0.0

virksomhedsoplysninger_17
0.8210510970187331

virksomhedsoplysninger_2
0.8210510970187331

virksomhedsoplysninger_4
0.8210510970187331

virksomhedsoplysninger_3
0.8210510970187331

virksomhedsoplysninger_1
0.8210510970187331

virksomhedsoplysninger_19
0.988118667541366

virksomhedsoplysninger_18
0.8286318244770027

virksomhedsoplysninger_21
0.17202420001457833

virksomhedsoplysninger_22
0.172534441285808

virksomhedsoplysninger_25
0.17442962315037538

virksomhedsoplysninger_24
0.17107660908229463

virksomhedsoplysninger_23
0.17457540637072672

virksomhedsoplysninger_20
0.17260733289598368

ejerkreds_aktiv_83
0.3701435964720461

ejerkreds_aktiv_16
0.32072308477294265

ejerkreds_aktiv_18
0.32276404985786133

ejerkreds_aktiv_24
0.3203586267220643

ejerkreds_aktiv_22
0.31839055324732124

ejerkreds_aktiv_20
0.3236387491799694

ejerkreds_aktiv_14
0.3194110357897806

ejerkreds_aktiv_15
0.31999416867118596

ejerkreds_aktiv_17
0.32013995189153727

ejerkreds_aktiv_23
0.32065019316276694

ejerkreds_aktiv_21
0.31839055324732124

ejerkreds_aktiv_19
0.3236387491799694

ejerkreds_aktiv_13
0.3200670602813616

ejerkreds_aktiv_62
0.5256214009767476

ejerkreds_ny_13
0.7734528755740214

ejerkreds_aktiv_64
0.5277352576718419

ejerkreds_ny_15
0.7750564909978861

ejerkreds_aktiv_70
0.5254756177563963

ejerkreds_ny_21
0.7730155259129674

ejerkreds_aktiv_68
0.5237991107223559

ejerkreds_ny_19
0.7721408265908594

ejerkreds_aktiv_66
0.5272979080107879

ejerkreds_ny_17
0.7741089000656024

ejerkreds_aktiv_60
0.5246738100444639

ejerkreds_ny_11
0.7733070923536701

ejerkreds_aktiv_61
0.5247467016546395

ejerkreds_ny_12
0.7736715504045485

ejerkreds_aktiv_63
0.5248924848749909

ejerkreds_ny_14
0.7737444420147241

ejerkreds_aktiv_69
0.5251840513156936

ejerkreds_ny_20
0.7734528755740214

ejerkreds_aktiv_67
0.5237991107223559

ejerkreds_ny_18
0.7721408265908594

ejerkreds_aktiv_65
0.5272979080107879

ejerkreds_ny_16
0.7741089000656024

ejerkreds_aktiv_59
0.5248924848749909

ejerkreds_ny_10
0.7740360084554267

ejerkreds_aktiv_10
0.06356148407318318

ejerkreds_aktiv_31
0.05984401195422407

ejerkreds_aktiv_96
0.29798090239813396

ejerkreds_aktiv_97
0.8140535024418689

ejerkreds_aktiv_47
0.0

ejerkreds_aktiv_12
0.0

ejerkreds_aktiv_48
0.0

ejerkreds_aktiv_50
0.0

ejerkreds_aktiv_49
0.0

ejerkreds_aktiv_3
0.885997521685254

ejerkreds_aktiv_2
0.8941613820249289

ejerkreds_aktiv_27
0.9998542167796487

ejerkreds_aktiv_29
0.9998542167796487

ejerkreds_aktiv_32
0.9998542167796487

ejerkreds_aktiv_124
0.9998542167796487

ejerkreds_aktiv_28
0.9998542167796487

ejerkreds_aktiv_30
0.9998542167796487

ejerkreds_aktiv_33
0.9998542167796487

ejerkreds_aktiv_125
0.9998542167796487

ejerkreds_aktiv_1
0.2909104162110941

ejerkreds_aktiv_130
0.2909104162110941

ejerkreds_aktiv_129
0.2909104162110941

ejerkreds_aktiv_128
0.2909104162110941

ejerkreds_aktiv_127
0.2909104162110941

ejerkreds_aktiv_7
0.8740432976164444

ejerkreds_aktiv_6
0.29258692324513447

ejerkreds_ny_8
0.8325679714264889

ejerkreds_aktiv_11
0.8325679714264889

ejerkreds_aktiv_41
0.7961221663386544

ejerkreds_aktiv_43
0.9976674684743786

ejerkreds_aktiv_44
0.8329324294773671

ejerkreds_aktiv_45
0.9997084335592973

ejerkreds_aktiv_46
0.954880093301261

ejerkreds_aktiv_35
0.9992710838982433

ejerkreds_aktiv_36
0.9849114366936366

ejerkreds_aktiv_37
0.9817770974560828

ejerkreds_aktiv_38
0.967636125082003

ejerkreds_aktiv_39
0.9998542167796487

ejerkreds_aktiv_40
0.986806618558204

ejerkreds_aktiv_131
0.9999271083898243

ejerkreds_aktiv_42
0.9988337342371894

ejerkreds_aktiv_99
0.9997084335592973

ejerkreds_ny_44
0.9998542167796487

ejerkreds_tidligere_10
1.0

ejerkreds_aktiv_87
0.9997084335592973

ejerkreds_ny_37
0.9998542167796487

ejerkreds_tidligere_8
1.0

ejerkreds_aktiv_53
1.0

ejerkreds_ny_3
1.0

ejerkreds_tidligere_2
1.0

ejerkreds_aktiv_25
0.034550623223267005

ejerkreds_aktiv_26
0.034550623223267005

ejerkreds_aktiv_126
0.3236387491799694

ejerkreds_ny_70
0.643268459800277

ejerkreds_tidligere_16
0.9834536044901232

ejerkreds_aktiv_104
0.3555652744369123

ejerkreds_ny_50
0.6638238938698156

ejerkreds_tidligere_12
0.9873897514396093

ejerkreds_aktiv_121
0.4969021065675341

ejerkreds_ny_66
0.7755667322691159

ejerkreds_tidligere_13
0.9878271011006633

ejerkreds_aktiv_103
0.3552737079962096

ejerkreds_ny_49
0.6649172680224507

ejerkreds_tidligere_11
0.9850572199139879

ejerkreds_aktiv_82
0.3533785261316422

ejerkreds_ny_30
0.6628763029375319

ejerkreds_tidligere_7
0.9841825205918798

ejerkreds_aktiv_107
0.7967781908302355

ejerkreds_ny_53
0.896785479991253

ejerkreds_aktiv_106
0.8620890735476346

ejerkreds_ny_52
0.9374589984692762

ejerkreds_aktiv_114
0.7411618922662001

ejerkreds_ny_60
0.8715649828704716

ejerkreds_aktiv_112
0.8178438661710037

ejerkreds_ny_58
0.921860193891683

ejerkreds_aktiv_113
1.0

ejerkreds_ny_59
1.0

ejerkreds_aktiv_111
0.7243968219257964

ejerkreds_ny_57
0.8639113638020264

ejerkreds_aktiv_110
0.8059625337123697

ejerkreds_ny_56
0.918361396603251

ejerkreds_aktiv_117
0.9300969458415337

ejerkreds_ny_63
0.9709162475399081

ejerkreds_aktiv_116
0.7952474670165464

ejerkreds_ny_62
0.90626138931409

ejerkreds_aktiv_109
0.9736132371164079

ejerkreds_ny_55
0.989212041694001

ejerkreds_aktiv_108
0.9930024054231358

ejerkreds_ny_54
0.9975945768642029

ejerkreds_aktiv_55
0.9579415409286391

ejerkreds_ny_5
0.9812668561848531

ejerkreds_aktiv_84
0.9819957722866098

ejerkreds_ny_31
0.9938771047452438

ejerkreds_aktiv_95
0.998469276186311

ejerkreds_ny_42
0.999562650338946

ejerkreds_aktiv_118
0.9120198265179678

ejerkreds_ny_69
0.9603469640644362

ejerkreds_aktiv_115
0.896785479991253

ejerkreds_ny_61
0.9528391282163423

ejerkreds_aktiv_89
0.8849770391427947

ejerkreds_ny_39
0.9422698447408703

ejerkreds_aktiv_85
0.9927837305926088

ejerkreds_ny_35
0.9983963845761353

ejerkreds_aktiv_101
0.8673372694802828

ejerkreds_ny_46
0.9451855091478971

ejerkreds_aktiv_54
0.5778846854727021

ejerkreds_ny_4
0.7857715576937094

ejerkreds_aktiv_56
0.6760696843793279

ejerkreds_ny_6
0.8392739995626504

ejerkreds_aktiv_81
0.9981048181354326

ejerkreds_ny_29
0.9978132516947299

ejerkreds_aktiv_58
0.9851301115241635

ejerkreds_ny_9
0.9962096362708652

ejerkreds_aktiv_100
1.0

ejerkreds_ny_45
1.0

ejerkreds_aktiv_52
1.0

ejerkreds_ny_2
1.0

ejerkreds_aktiv_74
1.0

ejerkreds_ny_25
0.9999271083898243

ejerkreds_aktiv_72
0.4457321962242146

ejerkreds_ny_23
0.7182010350608645

ejerkreds_aktiv_73
0.9923463809315548

ejerkreds_ny_24
0.9954807201691085

ejerkreds_aktiv_88
0.368612872658357

ejerkreds_ny_38
0.6730811283621255

ejerkreds_aktiv_91
0.41300386325533933

ejerkreds_ny_41
0.6995407828558933

ejerkreds_aktiv_90
0.5243822436037612

ejerkreds_ny_40
0.7908739704060063

ejerkreds_aktiv_105
0.9916903564399737

ejerkreds_ny_51
0.9978861433049057

ejerkreds_aktiv_71
0.577666010642175

ejerkreds_ny_22
0.7961221663386544

ejerkreds_aktiv_86
0.7327793570959983

ejerkreds_ny_36
0.8860704132954297

ejerkreds_tidligere_6
1.0

ejerkreds_tidligere_15
1.0

ejerkreds_aktiv_79
0.9994897587287703

ejerkreds_ny_28
1.0

ejerkreds_tidligere_5
1.0

ejerkreds_aktiv_98
0.9994897587287703

ejerkreds_ny_43
1.0

ejerkreds_tidligere_9
1.0

ejerkreds_aktiv_122
0.9994897587287703

ejerkreds_ny_68
1.0

ejerkreds_tidligere_14
1.0

ejerkreds_aktiv_51
0.9994897587287703

ejerkreds_ny_1
1.0

ejerkreds_tidligere_1
1.0

ejerkreds_aktiv_80
0.05984401195422407

ejerkreds_aktiv_102
0.05984401195422407

ejerkreds_aktiv_78
0.0

ejerkreds_ny_32
0.05984401195422407

ejerkreds_aktiv_34
0.027698811866754137

ejerkreds_aktiv_5
0.9531306946570449

ejerkreds_aktiv_75
0.9615132298272469

ejerkreds_ny_26
0.9901596326262847

ejerkreds_tidligere_3
0.9975216852540273

ejerkreds_aktiv_76
0.9615132298272469

ejerkreds_ny_27
0.9901596326262847

ejerkreds_tidligere_4
0.9975216852540273

ejerkreds_ny_48
0.7472847875209563

ejerkreds_ny_47
0.7472847875209563

ejerkreds_aktiv_123
0.3236387491799694

ejerkreds_ny_67
0.643268459800277

ejerkreds_aktiv_57
0.3236387491799694

ejerkreds_ny_7
0.643268459800277

ejerkreds_aktiv_120
0.3312194766382389

ejerkreds_ny_65
0.6585756979371674

ejerkreds_aktiv_119
0.3312194766382389

ejerkreds_ny_64
0.6585756979371674

ejerkreds_aktiv_4
0.7163787448064728

adresse_1
0.5122822363146002

adresse_2
0.6456738829360741

adresse_3
0.6579196734455864

adresse_4

0.6602522049712078

adresse_16
0.9992710838982433

ejerkreds_ny_33
0.9964283111013922

adresse_15
0.6041985567461186

adresse_5
0.9386981558422626

adresse_6
0.9983963845761353

adresse_10
0.9853487863546906

adresse_11
0.9989795174575407

adresse_7
0.8365041183759749

adresse_12
0.9582331073693418

adresse_9
0.9838180625410016

adresse_14
0.9989795174575407

adresse_8
0.9226620016036154

adresse_13
0.990305415846636

virksomhedsoplysninger_55
0.0

virksomhedsoplysninger_54
0.0

virksomhedsoplysninger_5
0.9954807201691085

virksomhedsoplysninger_10
0.9997084335592973

virksomhedsoplysninger_12
0.999781325169473

virksomhedsoplysninger_7
0.9954807201691085

virksomhedsoplysninger_8
0.9997084335592973

virksomhedsoplysninger_9
0.9998542167796487

virksomhedsoplysninger_13
0.999781325169473

virksomhedsoplysninger_11
0.999781325169473

virksomhedsoplysninger_6
0.9905240906771631

virksomhedsoplysninger_26
0.9966469859319192

virksomhedsoplysninger_27
0.999781325169473

virksomhedsoplysninger_28
1.0

virksomhedsoplysninger_29
0.996501202711568

virksomhedsoplysninger_34
0.9966469859319192

virksomhedsoplysninger_35
0.999781325169473

virksomhedsoplysninger_36
1.0

virksomhedsoplysninger_30
0.9966469859319192

virksomhedsoplysninger_31
0.999781325169473

virksomhedsoplysninger_32
1.0

virksomhedsoplysninger_33
1.0

virksomhedsoplysninger_37
1.0

virksomhedsoplysninger_38
1.0

virksomhedsoplysninger_49
1.0

virksomhedsoplysninger_40
1.0

virksomhedsoplysninger_52
1.0

virksomhedsoplysninger_48
1.0

virksomhedsoplysninger_45
1.0

virksomhedsoplysninger_39
1.0

virksomhedsoplysninger_51
1.0

virksomhedsoplysninger_44
1.0

virksomhedsoplysninger_41
1.0

virksomhedsoplysninger_43
1.0

virksomhedsoplysninger_46
1.0

virksomhedsoplysninger_42
1.0

virksomhedsoplysninger_50
1.0

virksomhedsoplysninger_53
1.0

virksomhedsoplysninger_47
1.0

virksomhedsoplysninger_14
0.919236095925359

virksomhedsoplysninger_15
0.9977403600845542

virksomhedsoplysninger_16
0.8742619724469713

sagsoplysninger_37
1.0

sagsoplysninger_3
0.0

sagsoplysninger_15
0.0

ejerkreds_ny_34
0.0

sagsoplysninger_14
0.0

sagsoplysninger_12
0.0

sagsoplysninger_13
0.0

sagsoplysninger_16
0.8731685982943364

sagsoplysninger_21
0.8731685982943364

sagsoplysninger_24
0.8731685982943364

sagsoplysninger_26
0.8703987171076609

sagsoplysninger_27
0.8728770318536336

sagsoplysninger_28
0.8731685982943364

sagsoplysninger_17
0.8814053502441869

sagsoplysninger_18
0.8241854362562869

sagsoplysninger_19
0.8228733872731249

sagsoplysninger_20
0.8434288213426635

sagsoplysninger_22
0.895692105838618

sagsoplysninger_23
0.9655951599970843

sagsoplysninger_25
0.0

sagsoplysninger_31
1.0

sagsoplysninger_32
0.9999271083898243

sagsoplysninger_33
1.0

sagsoplysninger_6
0.6683431737007071

sagsoplysninger_7
0.9913987899992711

sagsoplysninger_8
0.0

sagsoplysninger_9
0.9989795174575407

sagsoplysninger_10
0.8598294336321889

sagsoplysninger_11
0.8733143815146877

sagsoplysninger_34
1.0

sagsoplysninger_5
0.9967927691522706

sagsoplysninger_35
1.0

sagsoplysninger_4
1.0

risikomarkering_2
0.9936584299147169

risikomarkering_3
0.9996355419491216

risikomarkering_5
0.9999271083898243

risikomarkering_7
0.967198775420949

risikomarkering_8
0.9996355419491216

risikomarkering_10
0.9862963772869743

risikomarkering_11
0.998906625847365

risikomarkering_12
0.9397186383847219

risikomarkering_13
0.667687149209126

risikomarkering_14
0.8898607770245645

risikomarkering_16
0.9924921641519061

risikomarkering_17
0.9981777097456083

risikomarkering_18
0.9658867264377871

risikomarkering_19
0.9943144544062978

risikomarkering_20
0.9918361396603251

risikomarkering_21
0.976456009913259

risikomarkering_23
0.9960638530505139

risikomarkering_6
1.0

ejerkreds_aktiv_9
0.895692105838618

sagsoplysninger_2
0.0

ejerkreds_aktiv_8
1.0

sagsoplysninger_1
0.999781325169473

sagsoplysninger_30
0.0

risikomarkering_1
0.0

sagsoplysninger_36
0.0

target
0.0

In [22]:
# deleting all columns with a nan amount of 100%
drop_list = list()

# print all columns with 3 example samples
row_count = training.shape[0]
for (columnName, columnData) in training.iteritems():
    
    nan_count = 0
    for point in columnData:
        if str(point) == 'nan':
            nan_count += 1
            
    nan_percent = nan_count / row_count
    
    if nan_percent > 0.3:
        drop_list.append(columnName)

print(drop_list)

['ejerkreds_aktiv_93', 'virksomhedsoplysninger_17', 'virksomhedsoplysninger_2', 'virksomhedsoplysninger_4', 'virksomhedsoplysninger_3', 'virksomhedsoplysninger_1', 'virksomhedsoplysninger_19', 'virksomhedsoplysninger_18', 'ejerkreds_aktiv_83', 'ejerkreds_aktiv_16', 'ejerkreds_aktiv_18', 'ejerkreds_aktiv_24', 'ejerkreds_aktiv_22', 'ejerkreds_aktiv_20', 'ejerkreds_aktiv_14', 'ejerkreds_aktiv_15', 'ejerkreds_aktiv_17', 'ejerkreds_aktiv_23', 'ejerkreds_aktiv_21', 'ejerkreds_aktiv_19', 'ejerkreds_aktiv_13', 'ejerkreds_aktiv_62', 'ejerkreds_ny_13', 'ejerkreds_aktiv_64', 'ejerkreds_ny_15', 'ejerkreds_aktiv_70', 'ejerkreds_ny_21', 'ejerkreds_aktiv_68', 'ejerkreds_ny_19', 'ejerkreds_aktiv_66', 'ejerkreds_ny_17', 'ejerkreds_aktiv_60', 'ejerkreds_ny_11', 'ejerkreds_aktiv_61', 'ejerkreds_ny_12', 'ejerkreds_aktiv_63', 'ejerkreds_ny_14', 'ejerkreds_aktiv_69', 'ejerkreds_ny_20', 'ejerkreds_aktiv_67', 'ejerkreds_ny_18', 'ejerkreds_aktiv_65', 'ejerkreds_ny_16', 'ejerkreds_aktiv_59', 'ejerkreds_ny_10', 'ejerkreds_aktiv_97', 'ejerkreds_aktiv_3', 'ejerkreds_aktiv_2', 'ejerkreds_aktiv_27', 'ejerkreds_aktiv_29', 'ejerkreds_aktiv_32', 'ejerkreds_aktiv_124', 'ejerkreds_aktiv_28', 'ejerkreds_aktiv_30', 'ejerkreds_aktiv_33', 'ejerkreds_aktiv_125', 'ejerkreds_aktiv_7', 'ejerkreds_ny_8', 'ejerkreds_aktiv_11', 'ejerkreds_aktiv_41', 'ejerkreds_aktiv_43', 'ejerkreds_aktiv_44', 'ejerkreds_aktiv_45', 'ejerkreds_aktiv_46', 'ejerkreds_aktiv_35', 'ejerkreds_aktiv_36', 'ejerkreds_aktiv_37', 'ejerkreds_aktiv_38', 'ejerkreds_aktiv_39', 'ejerkreds_aktiv_40', 'ejerkreds_aktiv_131', 'ejerkreds_aktiv_42', 'ejerkreds_aktiv_99', 'ejerkreds_ny_44', 'ejerkreds_tidligere_10', 'ejerkreds_aktiv_87', 'ejerkreds_ny_37', 'ejerkreds_tidligere_8', 'ejerkreds_aktiv_53', 'ejerkreds_ny_3', 'ejerkreds_tidligere_2', 'ejerkreds_aktiv_126', 'ejerkreds_ny_70', 'ejerkreds_tidligere_16', 'ejerkreds_aktiv_104', 'ejerkreds_ny_50', 'ejerkreds_tidligere_12', 'ejerkreds_aktiv_121', 'ejerkreds_ny_66', 'ejerkreds_tidligere_13', 'ejerkreds_aktiv_103', 'ejerkreds_ny_49', 'ejerkreds_tidligere_11', 'ejerkreds_aktiv_82', 'ejerkreds_ny_30', 'ejerkreds_tidligere_7', 'ejerkreds_aktiv_107', 'ejerkreds_ny_53', 'ejerkreds_aktiv_106', 'ejerkreds_ny_52', 'ejerkreds_aktiv_114', 'ejerkreds_ny_60', 'ejerkreds_aktiv_112', 'ejerkreds_ny_58', 'ejerkreds_aktiv_113', 'ejerkreds_ny_59', 'ejerkreds_aktiv_111', 'ejerkreds_ny_57', 'ejerkreds_aktiv_110', 'ejerkreds_ny_56', 'ejerkreds_aktiv_117', 'ejerkreds_ny_63', 'ejerkreds_aktiv_116', 'ejerkreds_ny_62', 'ejerkreds_aktiv_109', 'ejerkreds_ny_55', 'ejerkreds_aktiv_108', 'ejerkreds_ny_54', 'ejerkreds_aktiv_55', 'ejerkreds_ny_5', 'ejerkreds_aktiv_84', 'ejerkreds_ny_31', 'ejerkreds_aktiv_95', 'ejerkreds_ny_42', 'ejerkreds_aktiv_118', 'ejerkreds_ny_69', 'ejerkreds_aktiv_115', 'ejerkreds_ny_61', 'ejerkreds_aktiv_89', 'ejerkreds_ny_39', 'ejerkreds_aktiv_85', 'ejerkreds_ny_35', 'ejerkreds_aktiv_101', 'ejerkreds_ny_46', 'ejerkreds_aktiv_54', 'ejerkreds_ny_4', 'ejerkreds_aktiv_56', 'ejerkreds_ny_6', 'ejerkreds_aktiv_81', 'ejerkreds_ny_29', 'ejerkreds_aktiv_58', 'ejerkreds_ny_9', 'ejerkreds_aktiv_100', 'ejerkreds_ny_45', 'ejerkreds_aktiv_52', 'ejerkreds_ny_2', 'ejerkreds_aktiv_74', 'ejerkreds_ny_25', 'ejerkreds_aktiv_72', 'ejerkreds_ny_23', 'ejerkreds_aktiv_73', 'ejerkreds_ny_24', 'ejerkreds_aktiv_88', 'ejerkreds_ny_38', 'ejerkreds_aktiv_91', 'ejerkreds_ny_41', 'ejerkreds_aktiv_90', 'ejerkreds_ny_40', 'ejerkreds_aktiv_105', 'ejerkreds_ny_51', 'ejerkreds_aktiv_71', 'ejerkreds_ny_22', 'ejerkreds_aktiv_86', 'ejerkreds_ny_36', 'ejerkreds_tidligere_6', 'ejerkreds_tidligere_15', 'ejerkreds_aktiv_79', 'ejerkreds_ny_28', 'ejerkreds_tidligere_5', 'ejerkreds_aktiv_98', 'ejerkreds_ny_43', 'ejerkreds_tidligere_9', 'ejerkreds_aktiv_122', 'ejerkreds_ny_68', 'ejerkreds_tidligere_14', 'ejerkreds_aktiv_51', 'ejerkreds_ny_1', 'ejerkreds_tidligere_1', 'ejerkreds_aktiv_5', 'ejerkreds_aktiv_75', 'ejerkreds_ny_26', 'ejerkreds_tidligere_3', 'ejerkreds_aktiv_76', 'ejerkreds_ny_27', 'ejerkreds_tidligere_4', 'ejerkreds_ny_48', 'ejerkreds_ny_47', 'ejerkreds_aktiv_123', 'ejerkreds_ny_67', 'ejerkreds_aktiv_57', 'ejerkreds_ny_7', 'ejerkreds_aktiv_120', 'ejerkreds_ny_65', 'ejerkreds_aktiv_119', 'ejerkreds_ny_64', 'ejerkreds_aktiv_4', 'adresse_1', 'adresse_2', 'adresse_3', 'adresse_4', 'adresse_16', 'ejerkreds_ny_33', 'adresse_15', 'adresse_5', 'adresse_6', 'adresse_10', 'adresse_11', 'adresse_7', 'adresse_12', 'adresse_9', 'adresse_14', 'adresse_8', 'adresse_13', 'virksomhedsoplysninger_5', 'virksomhedsoplysninger_10', 'virksomhedsoplysninger_12', 'virksomhedsoplysninger_7', 'virksomhedsoplysninger_8', 'virksomhedsoplysninger_9', 'virksomhedsoplysninger_13', 'virksomhedsoplysninger_11', 'virksomhedsoplysninger_6', 'virksomhedsoplysninger_26', 'virksomhedsoplysninger_27', 'virksomhedsoplysninger_28', 'virksomhedsoplysninger_29', 'virksomhedsoplysninger_34', 'virksomhedsoplysninger_35', 'virksomhedsoplysninger_36', 'virksomhedsoplysninger_30', 'virksomhedsoplysninger_31', 'virksomhedsoplysninger_32', 'virksomhedsoplysninger_33', 'virksomhedsoplysninger_37', 'virksomhedsoplysninger_38', 'virksomhedsoplysninger_49', 'virksomhedsoplysninger_40', 'virksomhedsoplysninger_52', 'virksomhedsoplysninger_48', 'virksomhedsoplysninger_45', 'virksomhedsoplysninger_39', 'virksomhedsoplysninger_51', 'virksomhedsoplysninger_44', 'virksomhedsoplysninger_41', 'virksomhedsoplysninger_43', 'virksomhedsoplysninger_46', 'virksomhedsoplysninger_42', 'virksomhedsoplysninger_50', 'virksomhedsoplysninger_53', 'virksomhedsoplysninger_47', 'virksomhedsoplysninger_14', 'virksomhedsoplysninger_15', 'virksomhedsoplysninger_16', 'sagsoplysninger_37', 'sagsoplysninger_16', 'sagsoplysninger_21', 'sagsoplysninger_24', 'sagsoplysninger_26', 'sagsoplysninger_27', 'sagsoplysninger_28', 'sagsoplysninger_17', 'sagsoplysninger_18', 'sagsoplysninger_19', 'sagsoplysninger_20', 'sagsoplysninger_22', 'sagsoplysninger_23', 'sagsoplysninger_31', 'sagsoplysninger_32', 'sagsoplysninger_33', 'sagsoplysninger_6', 'sagsoplysninger_7', 'sagsoplysninger_9', 'sagsoplysninger_10', 'sagsoplysninger_11', 'sagsoplysninger_34', 'sagsoplysninger_5', 'sagsoplysninger_35', 'sagsoplysninger_4', 'risikomarkering_2', 'risikomarkering_3', 'risikomarkering_5', 'risikomarkering_7', 'risikomarkering_8', 'risikomarkering_10', 'risikomarkering_11', 'risikomarkering_12', 'risikomarkering_13', 'risikomarkering_14', 'risikomarkering_16', 'risikomarkering_17', 'risikomarkering_18', 'risikomarkering_19', 'risikomarkering_20', 'risikomarkering_21', 'risikomarkering_23', 'risikomarkering_6', 'ejerkreds_aktiv_9', 'ejerkreds_aktiv_8', 'sagsoplysninger_1']

In [23]:
# dropping them
for columnName in drop_list:
    training.drop(columnName, axis=1, inplace=True)
    
training.head(5)

,virksomhedsRegistreringsId,ejerkreds_aktiv_92,ejerkreds_aktiv_94,virksomhedsoplysninger_21,virksomhedsoplysninger_22,virksomhedsoplysninger_25,virksomhedsoplysninger_24,virksomhedsoplysninger_23,virksomhedsoplysninger_20,ejerkreds_aktiv_10,...,sagsoplysninger_14,sagsoplysninger_12,sagsoplysninger_13,sagsoplysninger_25,sagsoplysninger_8,sagsoplysninger_2,sagsoplysninger_30,risikomarkering_1,sagsoplysninger_36,target
0,1,0,0,0.0,"-5,00e+06","-1,0e+06","2,87250000000000e-02","23,89750000000000",-500000.0,0.0,...,1,1,1,1,1,-79,0,0,2,False
1,2,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,1,1,1,1,1,-30,0,0,2,False
2,5,0,0,0.0,"-5,00e+06","0,0e+00","0,00000000000000e+00","12,95000000000000",0.0,0.0,...,1,1,1,1,1,-135,0,0,2,False
3,6,0,0,0.0,"-5,00e+06","-1,0e+06","1,93000000000000e-01","38,81500000000000",0.0,0.0,...,1,1,1,1,1,0,0,0,2,True
4,7,1,1,0.0,"-5,00e+06","-1,0e+06","4,71583333333333e-01","171,26750000000001",-500000.0,0.0,...,1,1,1,1,1,-21,1,0,2,False

In [24]:
# deleting columns with no variance
del_list = list()
for (columnName, columnData) in training.iteritems():
    unique_values = set()
    
    for point in columnData:
        point = str(point)
        unique_values.add(point)
    
    unique_values = list(unique_values)
    
    if len(unique_values) == 1:
        del_list.append(columnName)
    
print(del_list)

for columnName in del_list:
    training.drop(columnName, axis=1, inplace=True)

['sagsoplysninger_15', 'sagsoplysninger_14', 'sagsoplysninger_12', 'sagsoplysninger_13', 'sagsoplysninger_25', 'sagsoplysninger_8', 'risikomarkering_1']

In [25]:
# printing distribution of fraudulent to non fraudulent rows
print(training['target'].value_counts())

False    10335
True      3384
Name: target, dtype: int64

In [26]:
training.head(5)

,virksomhedsRegistreringsId,ejerkreds_aktiv_92,ejerkreds_aktiv_94,virksomhedsoplysninger_21,virksomhedsoplysninger_22,virksomhedsoplysninger_25,virksomhedsoplysninger_24,virksomhedsoplysninger_23,virksomhedsoplysninger_20,ejerkreds_aktiv_10,...,ejerkreds_ny_32,ejerkreds_aktiv_34,virksomhedsoplysninger_55,virksomhedsoplysninger_54,sagsoplysninger_3,ejerkreds_ny_34,sagsoplysninger_2,sagsoplysninger_30,sagsoplysninger_36,target
0,1,0,0,0.0,"-5,00e+06","-1,0e+06","2,87250000000000e-02","23,89750000000000",-500000.0,0.0,...,0.0,0.0,4,5,0,0,-79,0,2,False
1,2,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,0.0,0.0,6,5,0,0,-30,0,2,False
2,5,0,0,0.0,"-5,00e+06","0,0e+00","0,00000000000000e+00","12,95000000000000",0.0,0.0,...,0.0,0.0,9,10,0,0,-135,0,2,False
3,6,0,0,0.0,"-5,00e+06","-1,0e+06","1,93000000000000e-01","38,81500000000000",0.0,0.0,...,0.0,0.0,4,10,0,0,0,0,2,True
4,7,1,1,0.0,"-5,00e+06","-1,0e+06","4,71583333333333e-01","171,26750000000001",-500000.0,0.0,...,0.0,0.0,6,10,0,0,-21,1,2,False

In [27]:
# reaffirming datatypes
for (columnName, columnData) in training.iteritems():
    
    print(type(columnData[0]))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.float64'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'str'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.int64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.bool_'>

In [28]:
# saving base transformed data
training.to_csv('../data/base_transformed/training.csv', index = False)